version: '3'

services:
  # Serviço de Frontend
  opiniao-mais-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8686:8686' # Frontend rodando na porta 8686
    env_file:
      - /home/deploy/.envs/opiniao-mais-front.env

  # Serviço do Nginx Proxy Manager
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80' # Porta HTTP
      - '443:443' # Porta HTTPS
      - '81:81' # Porta para a interface de administração do Nginx Proxy Manager
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite # Usando SQLite para armazenar dados do Nginx Proxy Manager
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt # Para armazenar certificados SSL
    depends_on:
      - opiniao-mais-web
