version: '3'
services:
  opiniao-mais-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8686:8686'
    environment:
      - VITE_API_BASE_URL=http://154.53.37.30:86/api # Use o IP real do backend
      - NGINX_PORT=8686
    volumes:
      - ./nginx/templates:/etc/nginx/templates
