version: '3.8'

services:
  opiniao-mais-web:  
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: opiniao-mais-web  
    ports:
      - '8686:8686'
    environment:
      - NGINX_PORT=8686
    env_file:
      - .env
