version: '3'
services:
  opiniao-mais-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8686:8686'
    env_file:
      - /home/deploy/.envs/opiniao-mais-front.env # 🔹 Carrega as variáveis do .env
    volumes:
      - ./nginx/templates:/etc/nginx/templates
